services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata_fastapi_course:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
  fastapi_backend_service:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8001:8001"
      volumes:
        - .:/fastapi_backend_service
      env_file:
        - .env

volumes:
  pgdata_fastapi_course: